import SwiftUI

/// A theme the user can pick: one accent colour and, on iOS, one app icon.
///
/// The values live here as constants rather than only in the asset catalogue
/// because three consumers need the same numbers — SwiftUI reads the generated
/// catalogue, the icon script reads the gradient, and `ReachyThemeTests` reads the
/// accents to check them. One source, so a rendered colour cannot differ from a
/// verified one.
public enum ReachyTheme: String, CaseIterable, Sendable, Identifiable {
    case graphite
    case bronze
    case teal
    case indigo
    case orchid
    case rose

    /// What an absent or unrecognised stored value resolves to — the latter happens
    /// to anyone who downgrades to a build that predates a theme.
    public static let fallback = ReachyTheme.graphite

    public var id: String {
        rawValue
    }
}

public extension ReachyTheme {
    /// sRGB, one accent per appearance plus the two gradient stops the icon uses.
    struct Palette: Sendable, Equatable {
        public let light: UInt32
        public let dark: UInt32
        public let gradientTop: UInt32
        public let gradientBottom: UInt32
    }

    var palette: Palette {
        switch self {
        case .graphite:
            Palette(light: 0x3E4757, dark: 0xA9B6CC, gradientTop: 0x9AA6B8, gradientBottom: 0x3E4757)
        case .bronze:
            Palette(light: 0xB26708, dark: 0xA86D16, gradientTop: 0xFFC96B, gradientBottom: 0xB26708)
        case .teal:
            Palette(light: 0x00A0A8, dark: 0x4FD6DE, gradientTop: 0x5FE0CE, gradientBottom: 0x00A0A8)
        case .indigo:
            Palette(light: 0x4B47D6, dark: 0x8E8CF0, gradientTop: 0x9B9BF5, gradientBottom: 0x4B47D6)
        case .orchid:
            Palette(light: 0x9038D9, dark: 0xC58AF0, gradientTop: 0xE8AEFF, gradientBottom: 0x9038D9)
        case .rose:
            Palette(light: 0xD6248A, dark: 0xFF7ABA, gradientTop: 0xFFA8CE, gradientBottom: 0xD6248A)
        }
    }
}

public extension ReachyTheme {
    /// The colour set this theme resolves to. Generated by
    /// `Scripts/render-theme-colors.swift` — never hand-edited.
    var colorSetName: String {
        "Theme" + rawValue.prefix(1).uppercased() + rawValue.dropFirst()
    }

    /// Adaptive by construction: the asset catalogue carries both appearances, which
    /// is the only cross-platform way to build one — SwiftUI cannot make an adaptive
    /// `Color` from two literals, and a `UIColor`/`NSColor` fork would not compile
    /// for both platforms this module targets.
    var accent: Color {
        Color(colorSetName, bundle: .module)
    }
}

public extension ReachyTheme {
    /// The alternate app icon this theme selects, or `nil` for the primary one.
    ///
    /// iOS only — macOS has no alternate icons, which is why this is a name rather
    /// than an image and why `AppIconSwitcher` is the only caller. Each name must
    /// also appear in `ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES` in
    /// `Apps/Project.swift` and name a committed `<name>.icon` bundle;
    /// `ThemeIconNameTests` is what keeps the three in step, because a mismatch
    /// surfaces only as a failed `setAlternateIconName` on a device.
    var alternateIconName: String? {
        switch self {
        case .graphite: nil
        case .bronze: "AppIcon-Bronze"
        case .teal: "AppIcon-Teal"
        case .indigo: "AppIcon-Indigo"
        case .orchid: "AppIcon-Orchid"
        case .rose: "AppIcon-Rose"
        }
    }
}

public extension ReachyTheme {
    /// The theme's app icon as a swatch — what the picker draws instead of the icon,
    /// which exposes no thumbnail.
    ///
    /// **Not a copy of the icon.** Icon Composer's material is undocumented and is
    /// deliberately not modelled here: fitting it was tried against two themes'
    /// shipping renders and the channels disagree (graphite moves +20/+20/+20 at the
    /// top, rose +0/+24/+14), so a formula would be false precision that the next
    /// Xcode would invalidate anyway. What the same measurement _does_ establish, and
    /// what this reproduces, is the shape of the difference:
    ///
    /// - the gradient is **vertical** — leading and trailing edges sit within 5/255 of
    ///   each other through the whole body of the icon, so it is not diagonal;
    /// - `icon.json`'s two stops land at roughly **17 % and 83 %** of the icon's
    ///   height, not at its edges;
    /// - past those the material carries on **lighter at the top and darker at the
    ///   bottom**, which is why a swatch painted with the declared stops alone reads
    ///   flatter than the icon it stands for.
    ///
    /// The two magnitudes are a judgement in that measured direction, not a fit.
    var iconSwatch: LinearGradient {
        LinearGradient(
            stops: [
                .init(color: Self.blend(palette.gradientTop, toward: Self.swatchHighlight), location: 0),
                .init(color: Color(hex: palette.gradientTop), location: Self.swatchStopInset),
                .init(color: Color(hex: palette.gradientBottom), location: 1 - Self.swatchStopInset),
                .init(color: Self.blend(palette.gradientBottom, toward: Self.swatchShade), location: 1),
            ],
            startPoint: .top,
            endPoint: .bottom
        )
    }

    /// Where the declared stops render, measured off `AppIcon.icns` at 256 pt.
    private static let swatchStopInset = 0.17
    private static let swatchHighlight = 0.25
    private static let swatchShade = -0.15

    /// Blends a palette constant toward white (positive) or black (negative).
    ///
    /// A blend rather than an addition, so a channel already at full — orchid's blue,
    /// rose's red — lightens without dragging the hue after it, which is exactly what
    /// clamping an addition would do.
    private static func blend(_ hex: UInt32, toward amount: Double) -> Color {
        let target: Double = amount > 0 ? 1 : 0
        let weight = abs(amount)
        func channel(_ shift: UInt32) -> Double {
            let value = Double((hex >> shift) & 0xFF) / 255
            return value + (target - value) * weight
        }
        return Color(.sRGB, red: channel(16), green: channel(8), blue: channel(0), opacity: 1)
    }
}

public extension ReachyTheme {
    /// Colour names, not robot vocabulary — a translator gets the same six words a
    /// paint chart would use.
    var title: LocalizedStringResource {
        switch self {
        case .graphite: .reachy("Graphite")
        case .bronze: .reachy("Bronze")
        case .teal: .reachy("Teal")
        case .indigo: .reachy("Indigo")
        case .orchid: .reachy("Orchid")
        case .rose: .reachy("Rose")
        }
    }
}

public extension Color {
    /// A fixed sRGB colour from a palette constant. Not adaptive on purpose — the
    /// gradient stops describe an icon, which has one appearance.
    init(hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}
