import Prefire
import ReachyUI
import SwiftUI

/// Debug-only catalogue of every ReachyUI screen state, built from the same previews that back the
/// snapshot tests. `PreviewModels` is generated by `mise run storybook`.
@main
struct ReachyStorybookApp: App {
    var body: some Scene {
        WindowGroup {
            NavigationStack {
                PlaybookView(isComponent: true, previewModels: PreviewModels.models)
                    // SwiftUI hoists `.toolbar` and `.searchable` out of the scaled preview cards
                    // into the nearest visible bars, so without this the storybook wears every
                    // card's chrome at once — nine Refresh buttons and the log console's filter
                    // field. The list draws its own header, so the bars have nothing else to show.
                    .toolbar(.hidden, for: .navigationBar, .bottomBar)
            }
            .reachyThemeFromSettings()
        }
    }
}
