test_configuration:
  target: ReachyUI
  test_target_path: ${PROJECT_DIR}/ReachyUISnapshotTests
  template_file_path: PreviewTests.stencil
  sources:
    - ${PROJECT_DIR}/../Sources/ReachyDesign/Previews
    - ${PROJECT_DIR}/../Sources/ReachyUI/Previews
    - ${PROJECT_DIR}/../Sources/ReachyWidgetUI/Previews
    - ${PROJECT_DIR}/ReachyMini/Previews
  testable_imports:
    - ReachyDesign
    - ReachyKit
    - ReachyMedia
    - ReachySSH
    - ReachyWidgetUI
  snapshot_devices:
    - iPhone 16 Pro
    - iPad Pro 11
  simulator_device: "iPhone18,1"
  required_os: 27
  use_grouped_snapshots: false
  split_snapshot_directories: true
  preview_default_enabled: true

playbook_configuration:
  preview_default_enabled: true
  testable_imports:
    - ReachyDesign
    - ReachyUI
    - ReachyKit
    - ReachyMedia
    - ReachySSH
    - ReachyWidgetUI
